FROM litespeedtech/openlitespeed:1.7.18-lsphp81

ADD /openlitespeed/httpd_config.conf /usr/local/lsws/conf
ADD /openlitespeed/docker.conf /usr/local/lsws/conf/templates
ADD /openlitespeed/php.ini /usr/local/lsws/lsphp81/etc/php/8.1/litespeed